# Generated by Django 6.0 on 2026-01-01 13:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkspaceMemeber',
            new_name='WorkspaceMember',
        ),
    ]
